version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fitbot_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - NODE_ENV=production
      - MONGODB_URI=
      - JWT_SECRET=
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:3001,http://127.0.0.1:3001
      - OPEN_FOOD_FACTS_API_URL=https://world.openfoodfacts.org/api/v2
      - OPENROUTER_API_KEY=
      - OPENROUTER_API_URL=https://openrouter.ai/api/v1/chat/completions
      - OPENROUTER_MODEL=openai/gpt-3.5-turbo
      - ENABLE_EXTERNAL_AI=true
      - ENABLE_FOOD_SEARCH=true
      - ENABLE_NUTRITION_TRACKING=true
      - ENABLE_METRICS_ENDPOINT=true
      - ENABLE_HEALTH_CHECKS=true
      - LOG_LEVEL=info
      - LOG_FORMAT=combined
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - fitbot_network

  frontend:
    build: ./frontend
    container_name: fitbot_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - fitbot_network

volumes: {}

networks:
  fitbot_network:
    driver: bridge
